In [0]:
#@importing libraries
import pandas as pd
import numpy as np
import tensorflow as tf



In [8]:
tf.__version__

'2.2.0'

In [0]:
#importing dataset
dataset=pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values


In [0]:
#encoding categorical data
#for genf
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [38]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [40]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [0]:
#splitting dataset in to test set and train set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)


In [0]:
#featurescaling
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [0]:
#initializing the ANN
ann=tf.keras.models.Sequential()

In [0]:
#adding the input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [0]:
#adding the second hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [0]:
#adding the output player
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))


In [0]:
#training ANN
#compiling the ANN
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [78]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5457 - accuracy: 0.7841
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4686 - accuracy: 0.8034
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4394 - accuracy: 0.8110
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4288 - accuracy: 0.8194
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4233 - accuracy: 0.8223
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4192 - accuracy: 0.8250
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4158 - accuracy: 0.8234
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4123 - accuracy: 0.8271
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4077 - accuracy: 0.8274
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4032 - accura

In [79]:
##answer to the homework
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]])))

[[0.02665317]]


In [80]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

[[False]]


In [86]:
#predict the test set resuts
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)

print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [87]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1533   62]
 [ 209  196]]


0.8645